name: Build and Push the flask app("Hello World") to Jfrog Artifactory
on:
  push:
    branches:
      - main
      - feature/*
jobs:
  build-and-push:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
      
    - name: Log in to JFrog Artifactory
      uses: docker/login-action@v3
      with:
        registry: vigneshtrail.jfrog.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: vigneshtrail.jfrog.io/vignesh-docker/flask-app:actions
