name: Build and Push the flask app("Hello World") to Jfrog Artifactory
on:
  push:
    branches:
      - main
      - feature/*
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to JFrog Artifactory
      uses: docker/login-action@v3
      with:
        registry: vigneshtrail.jfrog.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: docker build -t vigneshtrail.jfrog.io/vignesh-docker/flask-app:actions .
      
    - name: Push Docker image
      run: docker push vigneshtrail.jfrog.io/vignesh-docker/flask-app:actions
    
    - name: Send email notification
      if: always() # Run whether the previous steps succeeded or failed
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ job.status == 'success' && 'Build Succeeded' || 'Build Failed' }}
        body: Build ${{ github.job }} in workflow ${{ github.workflow }} of ${{ github.repository }} ${{ job.status }}!
        to: winvicky1998@gmail.com
        from: GitHub Actions
