name: Build and Push the flask app("Hello World") to Jfrog Artifactory
on:
  push:
    branches:
      - main
      - feature/*
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to JFrog Artifactory
      uses: docker/login-action@v3
      with:
        registry: vigneshtrail.jfrog.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: docker build -t vigneshtrail.jfrog.io/vignesh-docker/flask-app:actions .
      
    - name: Push Docker image
      run: docker push vigneshtrail.jfrog.io/vignesh-docker/flask-app:actions
    
    - name: Send Teams notification
      if: always()
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.TEAMS_WEBHOOK }}
        title: "Build ${{ job.status }}"
        summary: "Build ${{ github.workflow }} ${{ job.status }}"
        text: "Repository: ${{ github.repository }}\nBranch: ${{ github.ref }}\nStatus: ${{ job.status }}"
        theme_color: ${{ job.status == 'success' && '00FF00' || 'FF0000' }}

    - name: Send email via Microsoft Graph API
      if: always()
      uses: azure/ms-graph-action@v1.0.0
      with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          scopes: 'https://graph.microsoft.com/.default'
          method: 'POST'
          uri: 'https://graph.microsoft.com/v1.0/users/${{ secrets.SENDER_EMAIL }}/sendMail'
          body: |
            {
              "message": {
                "subject": "Build ${{ job.status == 'success' && 'Succeeded ✅' || 'Failed ❌' }}",
                "body": {
                  "contentType": "HTML",
                  "content": "<p>Build <b>${{ github.job }}</b> in workflow <b>${{ github.workflow }}</b> of <b>${{ github.repository }}</b> ${{ job.status }}!</p><p>Repository: ${{ github.repository }}<br>Branch: ${{ github.ref_name }}<br>Commit: ${{ github.event.head_commit.message }}<br>See details: <a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Build Log</a></p>"
                },
                "toRecipients": [
                  {
                    "emailAddress": {
                      "address": "recipient@yourcompany.com"
                    }
                  }
                ]
              },
              "saveToSentItems": "true"
            }
