name: Build and Push the flask app("Hello World") to Jfrog Artifactory
on:
  push:
    branches:
      - main
      - feature/*
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Add Docker permissions
    - name: Set Docker permissions
      run: |
        sudo chmod 666 /var/run/docker.sock
      
    - name: Log in to JFrog Artifactory
      uses: docker/login-action@v3
      with:
        registry: vigneshtrail.jfrog.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: docker build -t vigneshtrail.jfrog.io/vignesh-docker/flask-app:actions .
      
    - name: Push Docker image
      run: docker push vigneshtrail.jfrog.io/vignesh-docker/flask-app:actions
